Retry connection without restarting init container
Instead of restarting the init container until the database is
available, retry connection in a loop with max 30 attempts with 2
seconds timeout each. So the init container fails after 1 minute db
connection attempts.

This reduces the amount of container restarts on the Kubernetes node.

diff --git a/templates/gitea/init.yaml b/templates/gitea/init.yaml
--- a/templates/gitea/init.yaml
+++ b/templates/gitea/init.yaml
@@ -42,13 +42,25 @@ stringData:
     set -euo pipefail
 
     {{- if include "db.servicename" . }}
-    echo 'Wait for database to become avialable...'
-    {
-      nc -vz -w2 {{ include "db.servicename" . }} {{ include "db.port" . }}
-    } || {
-      echo '...not ready within 2 seconds.'
-      exit 1
+    # Connection retry inspired by https://gist.github.com/dublx/e99ea94858c07d2ca6de
+    function test_db_connection() {
+      local RETRY=0
+      local MAX=30
+
+      echo 'Wait for database to become avialable...'
+      until [ "${RETRY}" -ge "${MAX}" ]; do
+        nc -vz -w2 {{ include "db.servicename" . }} {{ include "db.port" . }} && break
+        RETRY=$[${RETRY}+1]
+        echo "...not ready yet (${RETRY}/${MAX})"
+      done
+
+      if [ "${RETRY}" -ge "${MAX}" ]; then
+        echo "Database not reachable after '${MAX}' attempts!"
+        exit 1
+      fi
     }
+
+    test_db_connection
     {{- end }}
 
     echo '==== BEGIN GITEA CONFIGURATION ===='
